import { apiClient } from './api';
import {
  Workflow,
  WorkflowTemplate,
  WorkflowExecution,
  ApprovalRule,
  AutomationLogEntry,
  AutomationMetricsData,
  SimulationResult,
  WorkflowTriggerDefinition,
  WorkflowConditionDefinition,
  WorkflowActionDefinition,
} from '../types/automation';

export const TRIGGER_DEFINITIONS: WorkflowTriggerDefinition[] = [
  {
    id: 'meeting_completed',
    label: 'Meeting Completed',
    description: 'Triggers automatically when an AI transcript and summary process finishes.',
    iconName: 'Video',
    category: 'Meetings',
    defaultConfig: { meetingType: 'all', minDurationMinutes: 15 },
  },
  {
    id: 'meeting_approved',
    label: 'Meeting Approved',
    description: 'Triggers when executive host approves transcript & action items.',
    iconName: 'ShieldCheck',
    category: 'Meetings',
    defaultConfig: { autoApproveThreshold: 85 },
  },
  {
    id: 'task_created',
    label: 'Task Created',
    description: 'Triggers whenever an AI extraction creates a new task entry.',
    iconName: 'PlusSquare',
    category: 'Tasks',
    defaultConfig: { priority: 'all', requireAssignee: false },
  },
  {
    id: 'task_completed',
    label: 'Task Completed',
    description: 'Triggers when a task status shifts to Done or Verified.',
    iconName: 'CheckCircle2',
    category: 'Tasks',
    defaultConfig: { notifyAssignee: true },
  },
  {
    id: 'risk_detected',
    label: 'Risk Detected',
    description: 'Triggers when Reflection Agent flags a high or critical project risk.',
    iconName: 'ShieldAlert',
    category: 'Risk Management',
    defaultConfig: { severity: 'HIGH', confidenceMin: 80 },
  },
  {
    id: 'decision_approved',
    label: 'Decision Approved',
    description: 'Triggers when a key executive decision passes human approval gate.',
    iconName: 'FileCheck',
    category: 'Governance',
    defaultConfig: { stakeholderRole: 'Executive' },
  },
  {
    id: 'manual_trigger',
    label: 'Manual Trigger',
    description: 'Triggers on-demand via dashboard button or API call.',
    iconName: 'Play',
    category: 'Utility',
    defaultConfig: { payloadSchema: 'custom' },
  },
  {
    id: 'scheduled_trigger',
    label: 'Scheduled Trigger',
    description: 'Triggers periodically on cron schedule or daily interval.',
    iconName: 'CalendarClock',
    category: 'Utility',
    defaultConfig: { cronExpression: '0 9 * * 1-5', timezone: 'UTC' },
  },
];

export const CONDITION_DEFINITIONS: WorkflowConditionDefinition[] = [
  {
    id: 'confidence_threshold',
    label: 'If confidence > threshold',
    description: 'Evaluate if AI extraction confidence score meets requirement.',
    iconName: 'Brain',
    category: 'AI Telemetry',
    defaultConfig: { minConfidenceScore: 85 },
  },
  {
    id: 'risk_level',
    label: 'If risk = HIGH',
    description: 'Branch logic based on risk severity classification.',
    iconName: 'AlertTriangle',
    category: 'Governance',
    defaultConfig: { targetRisk: 'HIGH' },
  },
  {
    id: 'owner_exists',
    label: 'If owner exists',
    description: 'Check if an assigned owner/person exists for the payload.',
    iconName: 'UserCheck',
    category: 'Routing',
    defaultConfig: { fallbackOwner: 'engineering-leads@execflow.ai' },
  },
  {
    id: 'approval_received',
    label: 'If approval received',
    description: 'Check if designated approver signed off on the execution step.',
    iconName: 'ShieldCheck',
    category: 'Governance',
    defaultConfig: { timeoutHours: 24 },
  },
  {
    id: 'deadline_approaching',
    label: 'If deadline < 3 days',
    description: 'Evaluate time delta between current timestamp and target deadline.',
    iconName: 'Clock',
    category: 'Schedules',
    defaultConfig: { daysRemainingThreshold: 3 },
  },
  {
    id: 'meeting_type_match',
    label: 'If meeting type matches',
    description: 'Branch based on meeting taxonomy (e.g., Sprint, Client, Leadership).',
    iconName: 'Tag',
    category: 'Meetings',
    defaultConfig: { allowedTypes: ['Sprint Planning', 'Incident Review'] },
  },
];

export const ACTION_DEFINITIONS: WorkflowActionDefinition[] = [
  {
    id: 'create_calendar_event',
    label: 'Create Calendar Event',
    description: 'Schedule a follow-up or review meeting on Google / Outlook Calendar.',
    iconName: 'Calendar',
    category: 'Calendar',
    defaultConfig: { durationMinutes: 30, addZoomLink: true },
    requiresApprovalByDefault: false,
  },
  {
    id: 'create_github_issue',
    label: 'Create GitHub Issue',
    description: 'Dispatch issue payload directly into target GitHub repository.',
    iconName: 'GitPullRequest',
    category: 'DevOps',
    defaultConfig: { repo: 'execflow/core-platform', labels: ['ai-extracted', 'bug'] },
    requiresApprovalByDefault: true,
  },
  {
    id: 'create_jira_ticket',
    label: 'Create Jira Ticket',
    description: 'File a user story or bug ticket into Jira project workspace.',
    iconName: 'CheckSquare',
    category: 'DevOps',
    defaultConfig: { projectKey: 'EXEC', issueType: 'Task' },
    requiresApprovalByDefault: false,
  },
  {
    id: 'send_email',
    label: 'Send Email',
    description: 'Dispatch executive email summary or client notification.',
    iconName: 'Mail',
    category: 'Messaging',
    defaultConfig: { recipientType: 'Stakeholders', format: 'HTML' },
    requiresApprovalByDefault: true,
  },
  {
    id: 'post_slack_message',
    label: 'Post Slack Message',
    description: 'Post structured block kit update into dedicated Slack channel.',
    iconName: 'MessageSquare',
    category: 'Messaging',
    defaultConfig: { channel: '#executive-updates', botName: 'ExecFlow Assistant' },
    requiresApprovalByDefault: false,
  },
  {
    id: 'send_teams_notification',
    label: 'Send Teams Notification',
    description: 'Send adaptive card alert to Microsoft Teams channel.',
    iconName: 'Users',
    category: 'Messaging',
    defaultConfig: { teamChannel: 'Engineering Alerts' },
    requiresApprovalByDefault: false,
  },
  {
    id: 'create_reminder',
    label: 'Create Reminder',
    description: 'Set personal or team action item reminder ping.',
    iconName: 'Bell',
    category: 'Task Tools',
    defaultConfig: { alertOffsetMinutes: 60 },
    requiresApprovalByDefault: false,
  },
  {
    id: 'webhook_call',
    label: 'Webhook Call',
    description: 'Dispatch signed HTTPS POST payload to external API listener.',
    iconName: 'Globe',
    category: 'Integrations',
    defaultConfig: { method: 'POST', endpointUrl: 'https://api.execflow.ai/v1/webhook' },
    requiresApprovalByDefault: true,
  },
];

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'tmpl-sprint-planning',
    name: 'Sprint Planning Auto-Sync',
    description: 'Auto-extract tasks from Sprint Planning meetings, file Jira tickets, and post Slack team updates.',
    category: 'Sprint Planning',
    iconName: 'Zap',
    badgeText: 'Most Popular',
    nodesCount: 5,
    estimatedTimeSavedMinutes: 45,
    workflowData: {
      name: 'Sprint Planning Auto-Sync',
      description: 'Auto-extract tasks from Sprint Planning meetings, file Jira tickets, and post Slack team updates.',
      category: 'Sprint Planning',
      status: 'active',
      version: '1.2.0',
      successRate: 98,
      averageDurationMs: 1850,
      requiresApproval: false,
      createdBy: { id: 'usr-1', name: 'Sarah Jenkins', avatarUrl: '' },
      tags: ['Sprint', 'Jira', 'Slack'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 100, y: 150 },
          data: {
            label: 'Meeting Completed',
            description: 'Sprint Planning Session Finished',
            type: 'trigger',
            category: 'Meetings',
            iconName: 'Video',
            config: { meetingType: 'Sprint Planning' },
            linkedTool: 'MeetingTranscriptProcessor',
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 420, y: 150 },
          data: {
            label: 'If confidence > 85%',
            description: 'Verify task extraction accuracy score',
            type: 'condition',
            category: 'AI Telemetry',
            iconName: 'Brain',
            config: { minConfidenceScore: 85 },
          },
        },
        {
          id: 'node-3',
          type: 'custom',
          position: { x: 740, y: 80 },
          data: {
            label: 'Create Jira Ticket',
            description: 'File sprint backlog items into Jira',
            type: 'action',
            category: 'DevOps',
            iconName: 'CheckSquare',
            config: { projectKey: 'EXEC', issueType: 'Task' },
            linkedTool: 'JiraIntegrationEngine',
          },
        },
        {
          id: 'node-4',
          type: 'custom',
          position: { x: 740, y: 240 },
          data: {
            label: 'Post Slack Message',
            description: 'Send sprint commitments summary to #sprint-engineering',
            type: 'action',
            category: 'Messaging',
            iconName: 'MessageSquare',
            config: { channel: '#sprint-engineering' },
            linkedTool: 'SlackNotifierService',
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#6366f1' } },
        { id: 'e2-3', source: 'node-2', target: 'node-3', animated: true, label: 'True (>85%)', style: { stroke: '#10b981' } },
        { id: 'e2-4', source: 'node-2', target: 'node-4', animated: true, label: 'Always', style: { stroke: '#a855f7' } },
      ],
    },
  },
  {
    id: 'tmpl-project-kickoff',
    name: 'Project Kickoff Onboarding',
    description: 'When a new project kickoff meeting closes, create calendar follow-ups, GitHub repository milestones, and email client briefs.',
    category: 'Project Kickoff',
    iconName: 'Rocket',
    badgeText: 'New',
    nodesCount: 6,
    estimatedTimeSavedMinutes: 60,
    workflowData: {
      name: 'Project Kickoff Onboarding',
      description: 'When a new project kickoff meeting closes, create calendar follow-ups, GitHub repository milestones, and email client briefs.',
      category: 'Project Kickoff',
      status: 'active',
      version: '1.0.0',
      successRate: 95,
      averageDurationMs: 2400,
      requiresApproval: true,
      createdBy: { id: 'usr-2', name: 'Alex Rivera', avatarUrl: '' },
      tags: ['Kickoff', 'GitHub', 'Email'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 80, y: 150 },
          data: {
            label: 'Meeting Approved',
            description: 'Kickoff meeting notes approved by lead',
            type: 'trigger',
            category: 'Meetings',
            iconName: 'ShieldCheck',
            config: { meetingType: 'Project Kickoff' },
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 400, y: 150 },
          data: {
            label: 'Create GitHub Issue',
            description: 'Create epic issue for initial milestones',
            type: 'action',
            category: 'DevOps',
            iconName: 'GitPullRequest',
            config: { repo: 'execflow/client-portal' },
          },
        },
        {
          id: 'node-3',
          type: 'custom',
          position: { x: 720, y: 150 },
          data: {
            label: 'Send Email',
            description: 'Email executive brief to client stakeholders',
            type: 'action',
            category: 'Messaging',
            iconName: 'Mail',
            config: { recipientType: 'Client Contacts' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#6366f1' } },
        { id: 'e2-3', source: 'node-2', target: 'node-3', animated: true, style: { stroke: '#10b981' } },
      ],
    },
  },
  {
    id: 'tmpl-weekly-standup',
    name: 'Weekly Stand-up Task Digest',
    description: 'Summarize weekly standup blocker decisions, update Jira tasks, and dispatch a weekly digest email to team leads.',
    category: 'Weekly Stand-up',
    iconName: 'Calendar',
    badgeText: 'Automated',
    nodesCount: 4,
    estimatedTimeSavedMinutes: 30,
    workflowData: {
      name: 'Weekly Stand-up Task Digest',
      description: 'Summarize weekly standup blocker decisions, update Jira tasks, and dispatch a weekly digest email to team leads.',
      category: 'Weekly Stand-up',
      status: 'active',
      version: '2.1.0',
      successRate: 99,
      averageDurationMs: 1400,
      requiresApproval: false,
      createdBy: { id: 'usr-3', name: 'David Kim', avatarUrl: '' },
      tags: ['Standup', 'Digest', 'Email'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 100, y: 150 },
          data: {
            label: 'Scheduled Trigger',
            description: 'Every Friday at 4:00 PM UTC',
            type: 'trigger',
            category: 'Utility',
            iconName: 'CalendarClock',
            config: { cronExpression: '0 16 * * 5' },
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 420, y: 150 },
          data: {
            label: 'Send Email',
            description: 'Dispatch weekly engineering progress digest',
            type: 'action',
            category: 'Messaging',
            iconName: 'Mail',
            config: { recipientType: 'Engineering Managers' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#6366f1' } },
      ],
    },
  },
  {
    id: 'tmpl-risk-escalation',
    name: 'Risk Escalation Protocol',
    description: 'Automatically intercept high-severity risks identified in meetings, require executive approval gate, and post Teams alerts.',
    category: 'Risk Escalation',
    iconName: 'ShieldAlert',
    badgeText: 'Critical Security',
    nodesCount: 5,
    estimatedTimeSavedMinutes: 90,
    workflowData: {
      name: 'Risk Escalation Protocol',
      description: 'Automatically intercept high-severity risks identified in meetings, require executive approval gate, and post Teams alerts.',
      category: 'Risk Escalation',
      status: 'active',
      version: '1.5.0',
      successRate: 92,
      averageDurationMs: 3100,
      requiresApproval: true,
      createdBy: { id: 'usr-1', name: 'Sarah Jenkins', avatarUrl: '' },
      tags: ['Risk', 'Governance', 'Teams'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 80, y: 160 },
          data: {
            label: 'Risk Detected',
            description: 'High severity technical or budget risk flagged',
            type: 'trigger',
            category: 'Risk Management',
            iconName: 'ShieldAlert',
            config: { severity: 'HIGH' },
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 400, y: 160 },
          data: {
            label: 'If risk = HIGH',
            description: 'Filter critical project risks',
            type: 'condition',
            category: 'Governance',
            iconName: 'AlertTriangle',
            config: { targetRisk: 'HIGH' },
          },
        },
        {
          id: 'node-3',
          type: 'custom',
          position: { x: 720, y: 100 },
          data: {
            label: 'Send Teams Notification',
            description: 'Alert executive risk response squad',
            type: 'action',
            category: 'Messaging',
            iconName: 'Users',
            config: { teamChannel: 'Executive Risk Hub' },
          },
        },
        {
          id: 'node-4',
          type: 'custom',
          position: { x: 720, y: 260 },
          data: {
            label: 'Webhook Call',
            description: 'Dispatch emergency webhook payload to PagerDuty',
            type: 'action',
            category: 'Integrations',
            iconName: 'Globe',
            config: { endpointUrl: 'https://events.pagerduty.com/v2/enqueue' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#ef4444' } },
        { id: 'e2-3', source: 'node-2', target: 'node-3', animated: true, label: 'HIGH Risk', style: { stroke: '#f59e0b' } },
        { id: 'e2-4', source: 'node-2', target: 'node-4', animated: true, label: 'Emergency', style: { stroke: '#ef4444' } },
      ],
    },
  },
  {
    id: 'tmpl-client-followup',
    name: 'Client Follow-Up Dispatcher',
    description: 'Post client meetings, verify key decision approvals, generate calendar follow-ups, and dispatch personalized summary emails.',
    category: 'Client Follow-up',
    iconName: 'Users',
    badgeText: 'Client Portal',
    nodesCount: 4,
    estimatedTimeSavedMinutes: 40,
    workflowData: {
      name: 'Client Follow-Up Dispatcher',
      description: 'Post client meetings, verify key decision approvals, generate calendar follow-ups, and dispatch personalized summary emails.',
      category: 'Client Follow-up',
      status: 'active',
      version: '1.1.0',
      successRate: 97,
      averageDurationMs: 1650,
      requiresApproval: true,
      createdBy: { id: 'usr-2', name: 'Alex Rivera', avatarUrl: '' },
      tags: ['Client', 'Calendar', 'Email'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 100, y: 150 },
          data: {
            label: 'Meeting Completed',
            description: 'Client Review Meeting Concluded',
            type: 'trigger',
            category: 'Meetings',
            iconName: 'Video',
            config: { meetingType: 'Client Review' },
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 420, y: 150 },
          data: {
            label: 'Create Calendar Event',
            description: 'Schedule 14-day check-in review',
            type: 'action',
            category: 'Calendar',
            iconName: 'Calendar',
            config: { durationMinutes: 30 },
          },
        },
        {
          id: 'node-3',
          type: 'custom',
          position: { x: 740, y: 150 },
          data: {
            label: 'Send Email',
            description: 'Email executive summary report to client lead',
            type: 'action',
            category: 'Messaging',
            iconName: 'Mail',
            config: { recipientType: 'Client' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#6366f1' } },
        { id: 'e2-3', source: 'node-2', target: 'node-3', animated: true, style: { stroke: '#10b981' } },
      ],
    },
  },
  {
    id: 'tmpl-release-meeting',
    name: 'Release Readiness Verification',
    description: 'Ensure release meeting action items have assigned owners, verify approval gates, and create GitHub release tags automatically.',
    category: 'Release Meeting',
    iconName: 'GitPullRequest',
    badgeText: 'DevOps',
    nodesCount: 5,
    estimatedTimeSavedMinutes: 50,
    workflowData: {
      name: 'Release Readiness Verification',
      description: 'Ensure release meeting action items have assigned owners, verify approval gates, and create GitHub release tags automatically.',
      category: 'Release Meeting',
      status: 'active',
      version: '1.4.0',
      successRate: 96,
      averageDurationMs: 2100,
      requiresApproval: true,
      createdBy: { id: 'usr-3', name: 'David Kim', avatarUrl: '' },
      tags: ['Release', 'GitHub', 'Approval'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 90, y: 150 },
          data: {
            label: 'Decision Approved',
            description: 'Release signoff decision approved by VP',
            type: 'trigger',
            category: 'Governance',
            iconName: 'FileCheck',
            config: { stakeholderRole: 'VP Engineering' },
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 410, y: 150 },
          data: {
            label: 'If owner exists',
            description: 'Verify release manager assignment',
            type: 'condition',
            category: 'Routing',
            iconName: 'UserCheck',
            config: { fallbackOwner: 'release-squad@execflow.ai' },
          },
        },
        {
          id: 'node-3',
          type: 'custom',
          position: { x: 730, y: 150 },
          data: {
            label: 'Create GitHub Issue',
            description: 'Tag production deployment tracking issue',
            type: 'action',
            category: 'DevOps',
            iconName: 'GitPullRequest',
            config: { repo: 'execflow/production-release' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#6366f1' } },
        { id: 'e2-3', source: 'node-2', target: 'node-3', animated: true, style: { stroke: '#10b981' } },
      ],
    },
  },
  {
    id: 'tmpl-incident-review',
    name: 'Post-Mortem Incident Escalator',
    description: 'When an Incident Review meeting completes, extract remediation tasks, generate Jira tickets, and alert engineering leads.',
    category: 'Incident Review',
    iconName: 'AlertOctagon',
    badgeText: 'High Priority',
    nodesCount: 4,
    estimatedTimeSavedMinutes: 75,
    workflowData: {
      name: 'Post-Mortem Incident Escalator',
      description: 'When an Incident Review meeting completes, extract remediation tasks, generate Jira tickets, and alert engineering leads.',
      category: 'Incident Review',
      status: 'active',
      version: '1.0.1',
      successRate: 94,
      averageDurationMs: 2200,
      requiresApproval: false,
      createdBy: { id: 'usr-1', name: 'Sarah Jenkins', avatarUrl: '' },
      tags: ['Incident', 'Jira', 'PagerDuty'],
      nodes: [
        {
          id: 'node-1',
          type: 'custom',
          position: { x: 100, y: 150 },
          data: {
            label: 'Meeting Completed',
            description: 'Incident Post-Mortem Session Concluded',
            type: 'trigger',
            category: 'Meetings',
            iconName: 'Video',
            config: { meetingType: 'Incident Review' },
          },
        },
        {
          id: 'node-2',
          type: 'custom',
          position: { x: 420, y: 150 },
          data: {
            label: 'Create Jira Ticket',
            description: 'Create SEV-1 remediation task item',
            type: 'action',
            category: 'DevOps',
            iconName: 'CheckSquare',
            config: { projectKey: 'SEV', issueType: 'Bug' },
          },
        },
        {
          id: 'node-3',
          type: 'custom',
          position: { x: 740, y: 150 },
          data: {
            label: 'Post Slack Message',
            description: 'Broadcast post-mortem actions to #incident-response',
            type: 'action',
            category: 'Messaging',
            iconName: 'MessageSquare',
            config: { channel: '#incident-response' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true, style: { stroke: '#ef4444' } },
        { id: 'e2-3', source: 'node-2', target: 'node-3', animated: true, style: { stroke: '#10b981' } },
      ],
    },
  },
];

export const MOCK_APPROVAL_RULES: ApprovalRule[] = [
  {
    id: 'rule-1',
    name: 'Auto-Approve Low Risk Reminders',
    triggerType: 'task_created',
    actionType: 'create_reminder',
    condition: 'risk == LOW',
    riskLevelThreshold: 'LOW',
    approverRole: 'System Auto-Approval Engine',
    autoApproveEnabled: true,
    status: 'active',
    description: 'Always approve low-risk calendar and personal reminders without human pause.',
    appliedCount: 142,
  },
  {
    id: 'rule-2',
    name: 'Require Approval for External Code Issues',
    triggerType: 'meeting_completed',
    actionType: 'create_github_issue',
    condition: 'always',
    riskLevelThreshold: 'MEDIUM',
    approverRole: 'Engineering Manager',
    autoApproveEnabled: false,
    status: 'active',
    description: 'Require explicit human approval before creating GitHub issues or modifying codebase repos.',
    appliedCount: 88,
  },
  {
    id: 'rule-3',
    name: 'Manager Gate on Client Email Dispatches',
    triggerType: 'decision_approved',
    actionType: 'send_email',
    condition: 'recipient == Client',
    riskLevelThreshold: 'HIGH',
    approverRole: 'VP of Customer Success',
    autoApproveEnabled: false,
    status: 'active',
    description: 'Require manager approval before emailing external clients or partners automatically.',
    appliedCount: 56,
  },
  {
    id: 'rule-4',
    name: 'Webhook Security Verification Gate',
    triggerType: 'risk_detected',
    actionType: 'webhook_call',
    condition: 'payload.isExternal == true',
    riskLevelThreshold: 'HIGH',
    approverRole: 'Security Lead',
    autoApproveEnabled: false,
    status: 'active',
    description: 'Hold all external webhook API calls for security payload verification.',
    appliedCount: 31,
  },
];

export const MOCK_EXECUTIONS: WorkflowExecution[] = [
  {
    id: 'exec-101',
    workflowId: 'wf-1',
    workflowName: 'Sprint Planning Auto-Sync',
    status: 'success',
    triggerEvent: 'Meeting Completed: Q3 Roadmap Planning',
    startedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 12 + 1850).toISOString(),
    durationMs: 1850,
    stepsExecuted: 4,
    actionsTriggered: 2,
    approvalsTriggered: 0,
    retriesCount: 0,
    triggeredBy: 'AI Meeting Intelligence Agent',
    logs: [
      {
        id: 'log-1',
        timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        level: 'info',
        workflowId: 'wf-1',
        workflowName: 'Sprint Planning Auto-Sync',
        nodeId: 'node-1',
        nodeLabel: 'Meeting Completed',
        message: 'Received meeting completion hook for "Q3 Roadmap Planning" (ID: mtg-8823)',
      },
      {
        id: 'log-2',
        timestamp: new Date(Date.now() - 1000 * 60 * 12 + 300).toISOString(),
        level: 'info',
        workflowId: 'wf-1',
        workflowName: 'Sprint Planning Auto-Sync',
        nodeId: 'node-2',
        nodeLabel: 'If confidence > 85%',
        message: 'Evaluated AI Confidence Score: 94.2% >= 85%. Proceeding on TRUE branch.',
      },
      {
        id: 'log-3',
        timestamp: new Date(Date.now() - 1000 * 60 * 12 + 1100).toISOString(),
        level: 'success',
        workflowId: 'wf-1',
        workflowName: 'Sprint Planning Auto-Sync',
        nodeId: 'node-3',
        nodeLabel: 'Create Jira Ticket',
        message: 'Successfully generated 5 Jira user stories under project EXEC (Keys: EXEC-410..414)',
      },
      {
        id: 'log-4',
        timestamp: new Date(Date.now() - 1000 * 60 * 12 + 1850).toISOString(),
        level: 'success',
        workflowId: 'wf-1',
        workflowName: 'Sprint Planning Auto-Sync',
        nodeId: 'node-4',
        nodeLabel: 'Post Slack Message',
        message: 'Broadcasted interactive BlockKit card into #sprint-engineering channel.',
      },
    ],
  },
  {
    id: 'exec-102',
    workflowId: 'wf-2',
    workflowName: 'Risk Escalation Protocol',
    status: 'awaiting_approval',
    triggerEvent: 'Risk Detected: API Deprecation Window Conflict',
    startedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    durationMs: 3100,
    stepsExecuted: 2,
    actionsTriggered: 1,
    approvalsTriggered: 1,
    retriesCount: 0,
    triggeredBy: 'Reflection Intelligence Agent',
    logs: [
      {
        id: 'log-10',
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        level: 'warn',
        workflowId: 'wf-2',
        workflowName: 'Risk Escalation Protocol',
        nodeId: 'node-1',
        nodeLabel: 'Risk Detected',
        message: 'High Risk Flagged: "API Deprecation Window Conflict" (Severity: HIGH, Confidence: 91%)',
      },
      {
        id: 'log-11',
        timestamp: new Date(Date.now() - 1000 * 60 * 45 + 500).toISOString(),
        level: 'info',
        workflowId: 'wf-2',
        workflowName: 'Risk Escalation Protocol',
        nodeId: 'node-2',
        nodeLabel: 'If risk = HIGH',
        message: 'Condition matched risk level HIGH. Triggered executive approval rule rule-2.',
      },
      {
        id: 'log-12',
        timestamp: new Date(Date.now() - 1000 * 60 * 45 + 1200).toISOString(),
        level: 'warn',
        workflowId: 'wf-2',
        workflowName: 'Risk Escalation Protocol',
        message: 'Workflow execution paused at Approval Gate #app-551. Waiting for VP signoff.',
      },
    ],
  },
  {
    id: 'exec-103',
    workflowId: 'wf-3',
    workflowName: 'Client Follow-Up Dispatcher',
    status: 'success',
    triggerEvent: 'Decision Approved: Enterprise Architecture Proposal',
    startedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    completedAt: new Date(Date.now() - 1000 * 60 * 180 + 1650).toISOString(),
    durationMs: 1650,
    stepsExecuted: 3,
    actionsTriggered: 2,
    approvalsTriggered: 1,
    retriesCount: 0,
    triggeredBy: 'Human Approval Engine',
    logs: [
      {
        id: 'log-20',
        timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
        level: 'info',
        workflowId: 'wf-3',
        workflowName: 'Client Follow-Up Dispatcher',
        message: 'Human Approval verified for decision #dec-89. Executing downstream pipeline.',
      },
      {
        id: 'log-21',
        timestamp: new Date(Date.now() - 1000 * 60 * 180 + 900).toISOString(),
        level: 'success',
        workflowId: 'wf-3',
        workflowName: 'Client Follow-Up Dispatcher',
        message: 'Scheduled 14-day calendar review with Acme Corp CTOS.',
      },
      {
        id: 'log-22',
        timestamp: new Date(Date.now() - 1000 * 60 * 180 + 1650).toISOString(),
        level: 'success',
        workflowId: 'wf-3',
        workflowName: 'Client Follow-Up Dispatcher',
        message: 'Dispatched executive email recap to acme-leads@acme.com.',
      },
    ],
  },
];

export const MOCK_AUTOMATION_METRICS: AutomationMetricsData = {
  totalWorkflows: 14,
  activeWorkflows: 11,
  totalExecutions: 1284,
  successRate: 97.4,
  failureRate: 2.6,
  averageRuntimeMs: 1720,
  approvalRate: 98.1,
  timeSavedHours: 342,
  executionsTrend: [
    { date: 'Mon', success: 180, failed: 4, pending: 2 },
    { date: 'Tue', success: 210, failed: 3, pending: 1 },
    { date: 'Wed', success: 245, failed: 6, pending: 3 },
    { date: 'Thu', success: 195, failed: 2, pending: 0 },
    { date: 'Fri', success: 230, failed: 5, pending: 4 },
    { date: 'Sat', success: 90, failed: 1, pending: 0 },
    { date: 'Sun', success: 85, failed: 1, pending: 1 },
  ],
  topActions: [
    { name: 'Create Jira Ticket', count: 412, iconName: 'CheckSquare' },
    { name: 'Post Slack Message', count: 388, iconName: 'MessageSquare' },
    { name: 'Send Email', count: 215, iconName: 'Mail' },
    { name: 'Create GitHub Issue', count: 145, iconName: 'GitPullRequest' },
    { name: 'Create Calendar Event', count: 124, iconName: 'Calendar' },
  ],
  riskDistribution: [
    { level: 'Low Risk (Auto-Approved)', count: 850, color: '#10b981' },
    { level: 'Medium Risk (Standard)', count: 320, color: '#f59e0b' },
    { level: 'High Risk (Approval Required)', count: 114, color: '#ef4444' },
  ],
};

export const automationService = {
  async getWorkflows(): Promise<Workflow[]> {
    return WORKFLOW_TEMPLATES.map((tmpl, idx) => ({
      id: `wf-${idx + 1}`,
      name: tmpl.workflowData.name,
      description: tmpl.workflowData.description,
      category: tmpl.workflowData.category,
      status: tmpl.workflowData.status,
      version: tmpl.workflowData.version,
      nodes: tmpl.workflowData.nodes,
      edges: tmpl.workflowData.edges,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * (idx + 2)).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      lastRunAt: new Date(Date.now() - 1000 * 60 * 20 * (idx + 1)).toISOString(),
      successRate: tmpl.workflowData.successRate,
      executionCount: 140 + idx * 35,
      averageDurationMs: tmpl.workflowData.averageDurationMs,
      requiresApproval: tmpl.workflowData.requiresApproval,
      createdBy: tmpl.workflowData.createdBy,
      tags: tmpl.workflowData.tags,
    }));
  },

  async getWorkflowTemplates(): Promise<WorkflowTemplate[]> {
    return WORKFLOW_TEMPLATES;
  },

  async getExecutions(): Promise<WorkflowExecution[]> {
    return MOCK_EXECUTIONS;
  },

  async getApprovalRules(): Promise<ApprovalRule[]> {
    return MOCK_APPROVAL_RULES;
  },

  async getMetrics(): Promise<AutomationMetricsData> {
    return MOCK_AUTOMATION_METRICS;
  },

  async simulateWorkflow(workflow: Partial<Workflow>): Promise<SimulationResult> {
    const nodes = workflow.nodes || [];
    const steps = nodes.map((node, index) => {
      const isCondition = node.data.type === 'condition';
      const isAction = node.data.type === 'action';
      const requiresApproval = node.data.type === 'action' && (node.data.config?.requiresApproval || Boolean(workflow.requiresApproval));

      return {
        stepNumber: index + 1,
        nodeId: node.id,
        nodeLabel: node.data.label || 'Node Step',
        nodeType: node.data.type || 'action',
        status: requiresApproval ? ('paused_for_approval' as const) : ('success' as const),
        input: {
          payloadSource: index === 0 ? 'Trigger Payload: Meeting Transcript' : `Step ${index} Input Data`,
          nodeConfig: node.data.config || {},
        },
        output: {
          success: true,
          resultSummary: `Executed ${node.data.label} with status 200 OK`,
          confidenceScore: 92 + index,
          processedItemsCount: 4,
        },
        decisionPathBranch: isCondition ? ('true' as const) : undefined,
        confidenceScore: 92 + index,
        riskLevel: isAction ? ('LOW' as const) : ('MEDIUM' as const),
        approvalRequired: requiresApproval,
        expectedDurationMs: 350 + index * 200,
        logMessage: `[Simulation Engine] Evaluated ${node.data.label}. Status: OK`,
      };
    });

    return {
      executionId: `sim-${Date.now()}`,
      workflowId: workflow.id || 'wf-sim',
      workflowName: workflow.name || 'Simulated Workflow',
      totalSteps: steps.length,
      passedSteps: steps.filter((s) => s.status === 'success').length,
      hasApprovalGates: steps.some((s) => s.approvalRequired),
      overallStatus: steps.some((s) => s.status === 'paused_for_approval') ? 'approval_required' : 'completed',
      totalEstimatedDurationMs: steps.reduce((acc, curr) => acc + curr.expectedDurationMs, 0),
      steps,
      expectedOutputs: {
        totalActionsQueued: steps.filter((s) => s.nodeType === 'action').length,
        approvalRequiredNodes: steps.filter((s) => s.approvalRequired).map((s) => s.nodeLabel),
        estimatedSavingsMinutes: 35,
      },
    };
  },
};
