import React from 'react';
import { Clock, Zap, TrendingUp, Sparkles, DollarSign } from 'lucide-react';

interface TimeSavedCardProps {
  hoursSaved: number;
  totalMeetings: number;
}

export const TimeSavedCard: React.FC<TimeSavedCardProps> = ({
  hoursSaved,
  totalMeetings,
}) => {
  const estimatedHourlyRate = 125; // $125/hr executive engineering cost basis
  const costSavings = Math.round(hoursSaved * estimatedHourlyRate);
  const avgHoursSavedPerMeeting = Number((hoursSaved / Math.max(1, totalMeetings)).toFixed(1));

  return (
    <div className="bg-gradient-to-br from-indigo-900 via-slate-900 to-purple-950 text-white rounded-xl p-5 shadow-lg border border-indigo-700/50 space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-lg bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
            <Clock className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-1.5">
              Autonomous Time ROI Impact
              <Sparkles className="w-3.5 h-3.5 text-amber-300 animate-pulse" />
            </h3>
            <p className="text-xs text-indigo-200">
              Quantified productivity yield generated by AI meeting processing & action item generation
            </p>
          </div>
        </div>

        <span className="px-2.5 py-1 text-xs font-bold rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
          +32.4% Productivity Boost
        </span>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
        <div className="bg-slate-900/80 rounded-lg p-3 border border-indigo-800/40 space-y-1">
          <span className="text-xs text-indigo-300 font-medium block">Total Executive Hours Saved</span>
          <div className="flex items-baseline gap-1.5">
            <span className="text-3xl font-black text-white">{hoursSaved}</span>
            <span className="text-xs text-indigo-200 font-semibold">hours</span>
          </div>
          <p className="text-[11px] text-slate-400">
            Equivalent to 0.9 full-time engineering weeks
          </p>
        </div>

        <div className="bg-slate-900/80 rounded-lg p-3 border border-indigo-800/40 space-y-1">
          <span className="text-xs text-indigo-300 font-medium block">Monetary Value Recaptured</span>
          <div className="flex items-baseline gap-1">
            <DollarSign className="w-5 h-5 text-emerald-400 self-center" />
            <span className="text-3xl font-black text-emerald-400">{costSavings.toLocaleString()}</span>
          </div>
          <p className="text-[11px] text-slate-400">
            Calculated at $125/hr executive standard rate
          </p>
        </div>

        <div className="bg-slate-900/80 rounded-lg p-3 border border-indigo-800/40 space-y-1">
          <span className="text-xs text-indigo-300 font-medium block">Per-Meeting Efficiency Gain</span>
          <div className="flex items-baseline gap-1.5">
            <span className="text-3xl font-black text-cyan-300">{avgHoursSavedPerMeeting}</span>
            <span className="text-xs text-cyan-200 font-semibold">hrs / session</span>
          </div>
          <p className="text-[11px] text-slate-400">
            Auto-summarization & action item extraction
          </p>
        </div>
      </div>

      <div className="pt-2 flex flex-wrap items-center justify-between gap-2 text-xs text-indigo-200 border-t border-indigo-900/60">
        <div className="flex items-center gap-1.5">
          <Zap className="w-3.5 h-3.5 text-amber-400" />
          <span>Zero manual synthesis required for 100% of recorded meetings.</span>
        </div>
        <div className="flex items-center gap-1 text-emerald-300 font-medium">
          <TrendingUp className="w-3.5 h-3.5" />
          <span>On track to save 160+ hours this quarter</span>
        </div>
      </div>
    </div>
  );
};
